version: "3.0"
services:
  database:
    image: mongo:latest
    volumes:
      - ${DATA_FOLDER}/db:/data/db
  databaseadmin:
    image: mongo-express
    depends_on:
      - database
    ports:
      - 8081:8081
    links:
      - database:mongo
  daemon:
    image: spaceapi/daemon
    depends_on:
      - database
    expose:
      - 8080
    volumes:
      - ${DATA_FOLDER}/config:/etc/spaceapidaemon
  swagger:
    image: swaggerapi/swagger-ui
    depends_on:
      - daemon
    expose:
      - 8080
    environment:
      - API_URL=${SWAGGERURL}
  caddy:
    image: spaceapi/daemonproxy
    depends_on:
      - daemon
      - swagger
    ports:
      - 2015:2015
    environment:
      - SPACEAPIURL=${SPACEAPIURL}:2015
