version: "3.0"
services:
  daemon:
    build: .
    depends_on:
      - database
    ports:
        - 8080:8080
  database:
    image: mongo:latest
    volumes:
         - /opt/spaceapidaemon/db:/data/db