version: "3.0"
services:
  database:
    image: mongo:latest
    volumes:
      - ${DATA_FOLDER}/db:/data/db
  daemon:
    image: spaceapi/daemon
    build: spaceApiDaemon
    depends_on:
      - database
    expose:
      - 8080
    volumes:
      - ${DATA_FOLDER}/config:/etc/spaceapidaemon
  swagger:
    image: swaggerapi/swagger-ui
    depends_on:
      - daemon
    expose:
      - 8080
    environment:
      - API_URL=${SWAGGERURL}
  reverse_proxy:
    image: spaceapi/daemonproxy
    build: reverseProxy
    depends_on:
      - daemon
      - swagger
    ports:
      - 2015:80
