version: "3.0"
services:
  database:
    image: mongo:latest
    volumes:
      - /opt/spaceapidaemon/db:/data/db
  daemon:
    image: spaceapi/daemon
    depends_on:
      - database
    expose:
      - 8080
    volumes:
      - /opt/spaceapidaemon/config:/etc/spaceapidaemon
  swagger:
    image: swaggerapi/swagger-ui
    depends_on:
      - daemon
    expose:
      - 8080
    environment:
      - API_URL=${SWAGGERURL}
  caddy:
    build: caddy
    depends_on:
      - daemon
      - swagger
    ports:
      - 443:443
    environment:
      - SPACEAPIURL